[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
headless = true
port = 7860
address = "0.0.0.0"

[browser]
gatherUsageStats = false
# serverAddress removed (should be auto-detected by HF Proxy)

[theme]
base = "light"
backgroundColor = "#fdfbf7"
secondaryBackgroundColor = "#f9f8f4"
primaryColor = "#d97706"
textColor = "#334155"
font = "sans serif"
